Programming error...
LOG: SDSS(pid=3,filter='i'): getting tile urls for <SkyCoord (ICRS): (ra, dec) in deg
LOG: SDSS(pid=3,filter='i'):     (0., 0.)>
LOG: SDSS(pid=3,filter='i'): Fetching: http://legacysurvey.org/viewer/fits-cutout?ra=0.0&dec=0.0&layer=sdss2&bands=i&pixscale=0.262&size=1374
LOG: SDSS(pid=3,filter='i'): bytearray(b'<html><body><h1>503 Service Unavailable</h1>')
LOG: SDSS(pid=3,filter='i'): bytearray(b'No server is available to handle this request.')
LOG: SDSS(pid=3,filter='i'): bytearray(b'</body></html>')
LOG: SDSS(pid=3,filter='i'): bytearray(b'')
LOG: SDSS(pid=3,filter='i'): OSError: Empty or corrupt FITS file: Badly formatted FITS file: Cutout not found: Skipping...
LOG: SDSS[print](pid=3,filter='i'): ERROR: error creating FITS
LOG: SDSS[print](pid=3,filter='i'): TRACEBACK:
LOG: SDSS[print](pid=3,filter='i'): >Traceback (most recent call last):
LOG: SDSS[print](pid=3,filter='i'): >   File "/home/falon/django_server/cirada/Cutout_Core/core/survey_abc.py", line 532, in get_cutout
LOG: SDSS[print](pid=3,filter='i'): >     tiles   = self.get_tiles(position,size)
LOG: SDSS[print](pid=3,filter='i'): >   File "/home/falon/django_server/cirada/Cutout_Core/core/survey_abc.py", line 318, in get_tiles
LOG: SDSS[print](pid=3,filter='i'): >     hdul_list = [hdul_tup for hdul_tup in [self.get_fits(url) for url in self.request_urls_stack] if hdul_tup[0]]
LOG: SDSS[print](pid=3,filter='i'): >   File "/home/falon/django_server/cirada/Cutout_Core/core/survey_abc.py", line 318, in <listcomp>
LOG: SDSS[print](pid=3,filter='i'): >     hdul_list = [hdul_tup for hdul_tup in [self.get_fits(url) for url in self.request_urls_stack] if hdul_tup[0]]
LOG: SDSS[print](pid=3,filter='i'): >   File "/home/falon/django_server/cirada/Cutout_Core/core/survey_abc.py", line 307, in get_fits
LOG: SDSS[print](pid=3,filter='i'): >     raise Exception("error creating FITS")
LOG: SDSS[print](pid=3,filter='i'): > Exception: error creating FITS
LOG: SDSS(pid=3,filter='i'): [Position: 0.0, 0.0 at radius 3.0 arcmin]: Processing Status = 'error'.
LOG: SDSS(pid=3,filter='i'): Cutout at (RA, Dec) of (0.0, 0.0) degrees /w size=6.0 arcmin returned None.