Programming error...
LOG: SDSS(pid=4,filter='g'): getting tile urls for <SkyCoord (ICRS): (ra, dec) in deg
LOG: SDSS(pid=4,filter='g'):     (0., 0.)>
LOG: SDSS(pid=4,filter='g'): Fetching: http://legacysurvey.org/viewer/fits-cutout?ra=0.0&dec=0.0&layer=sdss2&bands=g&pixscale=0.262&size=1374
LOG: SDSS(pid=4,filter='g'): bytearray(b'<html><body><h1>503 Service Unavailable</h1>')
LOG: SDSS(pid=4,filter='g'): bytearray(b'No server is available to handle this request.')
LOG: SDSS(pid=4,filter='g'): bytearray(b'</body></html>')
LOG: SDSS(pid=4,filter='g'): bytearray(b'')
LOG: SDSS(pid=4,filter='g'): OSError: Empty or corrupt FITS file: Badly formatted FITS file: Cutout not found: Skipping...
LOG: SDSS[print](pid=4,filter='g'): ERROR: error creating FITS
LOG: SDSS[print](pid=4,filter='g'): TRACEBACK:
LOG: SDSS[print](pid=4,filter='g'): >Traceback (most recent call last):
LOG: SDSS[print](pid=4,filter='g'): >   File "/home/falon/django_server/cirada/Cutout_Core/core/survey_abc.py", line 532, in get_cutout
LOG: SDSS[print](pid=4,filter='g'): >     tiles   = self.get_tiles(position,size)
LOG: SDSS[print](pid=4,filter='g'): >   File "/home/falon/django_server/cirada/Cutout_Core/core/survey_abc.py", line 318, in get_tiles
LOG: SDSS[print](pid=4,filter='g'): >     hdul_list = [hdul_tup for hdul_tup in [self.get_fits(url) for url in self.request_urls_stack] if hdul_tup[0]]
LOG: SDSS[print](pid=4,filter='g'): >   File "/home/falon/django_server/cirada/Cutout_Core/core/survey_abc.py", line 318, in <listcomp>
LOG: SDSS[print](pid=4,filter='g'): >     hdul_list = [hdul_tup for hdul_tup in [self.get_fits(url) for url in self.request_urls_stack] if hdul_tup[0]]
LOG: SDSS[print](pid=4,filter='g'): >   File "/home/falon/django_server/cirada/Cutout_Core/core/survey_abc.py", line 307, in get_fits
LOG: SDSS[print](pid=4,filter='g'): >     raise Exception("error creating FITS")
LOG: SDSS[print](pid=4,filter='g'): > Exception: error creating FITS
LOG: SDSS(pid=4,filter='g'): [Position: 0.0, 0.0 at radius 3.0 arcmin]: Processing Status = 'error'.
LOG: SDSS(pid=4,filter='g'): Cutout at (RA, Dec) of (0.0, 0.0) degrees /w size=6.0 arcmin returned None.